In [1]:
import pandas as pd

In [6]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})
 
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [7]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [8]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [9]:
pd.merge(employees, departments ,on="DeptID") #inner join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [12]:
pd.merge(employees,departments,on="DeptID",how= "left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [13]:
pd.merge(employees,departments,on="DeptID",how= "right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [14]:
pd.merge(employees,departments,on="DeptID",how="outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [32]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"],"Score": [90, 80]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"],"ID": [1,2]})

In [28]:
df2

      Name  ID
0  Charlie   1
1    David   2

In [33]:
df1

    Name  Score
0  Alice     90
1    Bob     80

In [34]:
pd.concat([df1,df2])

      Name  Score   ID
0    Alice   90.0  NaN
1      Bob   80.0  NaN
0  Charlie    NaN  1.0
1    David    NaN  2.0

In [35]:
pd.concat([df1,df2],axis=1)

    Name  Score     Name  ID
0  Alice     90  Charlie   1
1    Bob     80    David   2